# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kaslotappservice(kaslotappserviceslotone)

on:
  push:
    branches:
      - bluegreen

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.14.1'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kaslotappservice'
        slot-name: 'kaslotappserviceslotone'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_38f0c7e808f340168b9c8d19a0b5de4b }}
        package: .